// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy6QMVN9YpQbTaWagzboQ1rQ6EcRY4a64',
    appId: '1:841707704604:web:653718837921fa77b52ad9',
    messagingSenderId: '841707704604',
    projectId: 'shopping-app-69e18',
    authDomain: 'shopping-app-69e18.firebaseapp.com',
    databaseURL: 'https://shopping-app-69e18-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-69e18.appspot.com',
    measurementId: 'G-4QG98DB732',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG07aqv3AHmryAN5lTKCZis2yZdDn-Q9U',
    appId: '1:841707704604:android:33605ad8c62cdee6b52ad9',
    messagingSenderId: '841707704604',
    projectId: 'shopping-app-69e18',
    databaseURL: 'https://shopping-app-69e18-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-69e18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK2_gY3-407NTGOAvBxqsOJQC2wNIj25c',
    appId: '1:841707704604:ios:60aa3e3a8d0f9ca4b52ad9',
    messagingSenderId: '841707704604',
    projectId: 'shopping-app-69e18',
    databaseURL: 'https://shopping-app-69e18-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-69e18.appspot.com',
    iosClientId: '841707704604-vjud58r99ucstl57olei8eiucmura68g.apps.googleusercontent.com',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK2_gY3-407NTGOAvBxqsOJQC2wNIj25c',
    appId: '1:841707704604:ios:60aa3e3a8d0f9ca4b52ad9',
    messagingSenderId: '841707704604',
    projectId: 'shopping-app-69e18',
    databaseURL: 'https://shopping-app-69e18-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-69e18.appspot.com',
    iosClientId: '841707704604-vjud58r99ucstl57olei8eiucmura68g.apps.googleusercontent.com',
    iosBundleId: 'com.example.productApp',
  );
}
